/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package f.ape;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int btn_contNumDisc=0x7f050006;
        public static final int btn_gerirDisciplinas=0x7f050007;
        public static final int btn_opcoes=0x7f05000a;
        public static final int btn_sair=0x7f05000b;
        public static final int btn_sec=0x7f050000;
        public static final int btn_simulador=0x7f050009;
        public static final int btn_start=0x7f050003;
        public static final int btn_sup=0x7f050001;
        public static final int btn_visualizador=0x7f050008;
        public static final int check_intervalo=0x7f050005;
        public static final int textView1=0x7f050002;
        public static final int txt_numDisc=0x7f050004;
    }
    public static final class layout {
        public static final int escensino=0x7f030000;
        public static final int main=0x7f030001;
        public static final int menucriahorario=0x7f030002;
        public static final int menunumdisc=0x7f030003;
        public static final int menuprincipal=0x7f030004;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
